### ISSUE TITLE
khi nào thì cần chuyển app cũ?

### ISSUE THREAD

**Issue by lucreck** [Haravan/docs-omni#13]
@lmcuong25 em thấy bên mình có cập nhật một mục là chuyển app cũ thì việc chuyển app này sẽ cần thiết khi nào hay có thời điểm nào sẽ bắt buộc phải chuyển không?

**Comment by lmcuong25** [comment]
Hi @lucreck  , việc chuyển app này làm càng sớm càng tốt. Dealline là 28/2/2020.
