### ISSUE TITLE
Không thể cập nhật thông tin của khách hàng qua Omni API

### ISSUE THREAD

**Issue by smonv** [Haravan/docs-omni#20]
Hiện tại khi sử dụng endpoint để cập nhật thông tin của khách hàng, data gửi lên có hay không có trường `phone` (đại diện cho số điện thoại) thì response trả về đều là lỗi `Số điện thoại đã được sử dụng.` 

# Request:

`PUT https://apis.haravan.com/com/customers/{id}.json`

```json
{
	"customer": {
		"gender": 0
	}
}
```

# Response

HTTP Status: `422`

```json
{
  "errors": "Số điện thoại đã được sử dụng."
}
```

<img width="951" alt="Screen Shot 2020-03-18 at 11 24 23" src="https://user-images.githubusercontent.com/8962973/76925267-6c415880-690b-11ea-8e07-cb563e65f835.png">

**Comment by lmcuong25** [comment]
Em test thì thấy API vẩn hoạt động bình thường.

anh @smonv có thể cung cấp thêm customer_id để  em kiểm tra thêm được chứ?

**Comment by smonv** [comment]
@lmcuong25 Cảm ơn anh đã kiểm tra. Em cũng nhận thấy lỗi này chỉ xảy ra với một vài trường hợp.

`1029510622` là 1 trong những customer id bị lỗi này.

**Comment by smonv** [comment]
Hi @lmcuong25 

Về lỗi này a đã có phát hiện gì chưa? Hiện tại e vẫn thấy với 1 số customer, việc cập nhật vẫn bị lỗi.

**Comment by lmcuong25** [comment]
Hi @smonv 
em test thì thấy API vẩn hoạt động bình thường.
nhờ anh email về support@haravan.com, để team Haravan hỗ trợ chi tiết hơn.
thanks!
