### ISSUE TITLE
enable CORS cho Client khi request Api bằng Private App

### ISSUE THREAD

**Issue by lehoangphan** [Haravan/docs-omni#21]
mình tạo 1 Private App , tuy đã request test api thành công bằng Postman 
tuy nhiên khi request Api bằng Angular thì bị dính CORS ( Cross-Origin ) 

tuy nhiên phía server không allow header 'Access-Control-Allow-Origin': "*"

cho mình xin giải pháp dể request, 
cám ơn

**Comment by lmcuong25** [comment]
API chỉ cho phép call từ server to server . không hỗ trợ từ client call trực tiếp vào server.
Việc call từ client vào server api là không an toàn ( Private key để lộ trên client ).

**Comment by lehoangphan** [comment]
cám ơn rất nhiều
